pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    
    environment {
    DOCKER_HOST = "unix:///run/user/1000/podman/podman.sock"
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'podman run --rm -v $PWD:/app -w /app node:lts-buster-slim npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'podman run --rm -v $PWD:/app -w /app node:lts-buster-slim ./jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh 'podman run --rm -v $PWD:/app -w /app node:lts-buster-slim ./jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'podman run --rm -v $PWD:/app -w /app node:lts-buster-slim ./jenkins/scripts/kill.sh'
            }
        }
    }
}
